coinbase/mesh-geth-sdk

.github/workflows/ci.yml
=> [fix] change master to main

.github/workflows/ci.yml
Fixes # .
Since we moved back to master, revert pipeline from master to main to run Actions on master
=> revert main to master

README.md
Changed the header for Testing to fit the new template.
=> (nit) Update Testing header in README

.gitignore, examples/ethereum/Makefile, examples/ethereum/config/config.go, examples/ethereum/docker-compose.yml, services/block_service.go
Fixes # .
We want to enable rosetta-eth in dev mode
add docker-compose to spin up eth in dev
=> Support ethereum dev mode

services/mapper.go, services/mapper_test.go
Fixes # .
sync with another repo, and that repo has successfully  run ~3days
=> fix-operation-index-conflicts

client/types.go
Signed-off-by: Jingfu Wang <jingfu.wang@coinbase.com>
Add tx receipt status
=> Add tx receipt status

services/construction/construction_service.go, services/construction/construction_service_test.go, services/construction/preprocess_test.go
fixing the bug : 2023/02/17 22:42:26 strconv.ParseInt: parsing "-23946292673190280600": value out of range
and revert previous pr
=> change value range

.github/scripts/populate_txns.py, services/construction/construction_service.go
=> support delegation

client/types.go, services/block_service.go, services/mapper.go
=> feat: support ERC20 deposit and withdrawal event

services/mapper.go
=> fix: ERC20 topics number issue

client/types.go, services/mapper.go
=> fix: ERC20 withdrawal

types/errors.go
=> fix: error code issue

client/address.go, client/client.go, services/construction/metadata.go, services/construction/parse.go, services/construction/payloads.go, services/construction/preprocess.go, services/mapper.go
Not all downstream services support EIP55, remove EIP55 support for the time being
=> refactor: remove EIP55 support

services/block_service.go
=> fix: ignore issue tx

services/block_service.go
=> refactor: remove contract filter

services/block_service.go
Fixes # .
/block rosetta api is slow where there are spam contract interactions exists in a block. It happens in [base](https://basescan.org/tx/0x1e610911941f92f4d51632785e91341a2bb5632966261484d1e5bb534249c957#eventlog) and [bsc](https://testnet.bscscan.com/block/34383039). It will cause indexer timeout and paused network processing in the end. 
The root cause is when populate transactions for a block we will need to call `GetContractCurrency` for each transaction and it takes time. For spam contract above ^ they should all be same so we could cache it instead.
Before: /block request takes 8 minutes for this bsc-testnet [block](https://testnet.bscscan.com/tx/0x2499fe9b7ac72f644039f2b7c8f079988e31cd36c465b3ea5d8f227eece80ce7)
After: /block request takes 2 seconds for this bsc-testnet …
=> Add cache to GetContractCurrency

client/client.go, configuration/configuration.go
=> feat: add priority fee adjuster

services/construction/metadata.go
=> fix: hot fix for L1 data fee

services/construction/metadata.go
=> fix: hot fix to calculate contract data

client/client.go, services/construction/metadata.go
=> docs: clean up

client/client.go
=> refactor: priority fee

.github/scripts/setup.sh, CONTRIBUTING.md, README.md, examples/ethereum/Makefile, examples/ethereum/readme.md
=> rename to Mesh

client/client.go, configuration/configuration.go, mocks/services/client.go, services/block_service.go, services/construction/types.go
Fixes # .
CL:
* support customized block body with new tx type
=> feat: support customized tx body

.github/workflows/ci.yml
=> use web3 5.31.3

go.mod, go.sum
update mesh-sdk-go to the latest version
=> update mesh-sdk-go to v0.8.9
